service: helpinho-node-aws
provider:
  name: aws
  runtime: nodejs18.x
functions:
  app:
    handler: dist/app.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}
plugins:
   - serverless-offline

resources:
  Resources:
    HelpinhoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: helpinho-node-aws
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: TYPE
            KeySchema:
            - AttributeName: TYPE
              KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput: 
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
